version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: todolist-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: todolist
      MYSQL_USER: 'todolist'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3307:3306

  redis:
    image: 'redis:6-alpine'
    container_name: todolist-redis
    ports:
      - 6380:6379

  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    container_name: sotadex-zookeeper
    ports:
      - 2183:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./.docker/zookeeper:/var/lib/zookeeper

  kafka:
    image: 'bitnami/kafka:2.6.0'
    container_name: todolist-kafka
    user: root
    ports:
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=10485760
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
    depends_on:
      - zookeeper
    volumes:
      - ./.docker/kafka:/bitnami/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: 'no'
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
      JVM_OPTS: '-Xms160M -Xmx480M -Xss1800K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
    depends_on:
      - 'kafka'

  mosquitto:
    image: eclipse-mosquitto
    # volumes:
    #   - ./:/mosquitto/:rw
    ports:
      - 1883:1883
