version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: todolist-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: todolist
      MYSQL_USER: 'todolist'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3307:3306

  redis:
    image: 'redis:6-alpine'
    container_name: todolist-redis
    ports:
      - 6380:6379
